package main

// Redundant blockFacesByType removed. Managed in block_registry.go.

var allBlocks = []byte{
	blockGrass,
	blockDirt,
	blockStone,
	blockCobblestone,
	blockSand,
	blockSandstone,
	blockGravel,
	blockSnow,
	blockIce,

	// Wood
	blockLog,
	blockLogBirch,
	blockLogSpruce,
	blockLeaves,
	blockLeavesBirch,
	blockLeavesSpruce,
	blockPlank,
	blockPlankOak,
	blockPlankBirch,
	blockPlankSpruce,

	// Vegetation
	blockCactus,
	blockDeadBush,
	blockRose,
	blockDandelion,
	blockTallGrass,

	// Misc
	blockGlass,
	blockTorch,
	blockBedrock,
	blockCraftingTable,
	blockChest,
	blockFurnace,
	blockTNT,
	blockBed,
	blockWhiteWool,
	itemWheatSeeds,
	itemWheat,
	itemBread,
	itemPotato,
	itemCarrot,
	itemBakedPotato,
	itemWoodHoe,
	itemStoneHoe,
	itemIronHoe,
	itemDiamondHoe,
	itemGoldHoe,

	// Liquids
	blockWater,
	blockLava,

	// Ores
	blockCoalOre,
	blockIronOre,
	blockGoldOre,
	blockDiamondOre,
	blockLapisOre,

	// Special Blocks
	blockGlowstone,
	blockObsidian,
	blockDiamondBlock,
	blockGoldBlock,
	blockIronBlock,
	blockCoalBlock,

	// Tools
	itemWoodPickaxe,
	itemStonePickaxe,
	itemIronPickaxe,
	itemDiamondPickaxe,
	itemGoldPickaxe,

	itemWoodShovel,
	itemStoneShovel,
	itemIronShovel,
	itemDiamondShovel,
	itemGoldShovel,

	itemWoodAxe,
	itemStoneAxe,
	itemIronAxe,
	itemDiamondAxe,
	itemGoldAxe,
	itemGoldHelmet,
	itemGoldChestplate,
	itemGoldLeggings,
	itemGoldBoots,
	itemIronHelmet,
	itemIronChestplate,
	itemIronLeggings,
	itemIronBoots,
	itemDiamondHelmet,
	itemDiamondChestplate,
	itemDiamondLeggings,
	itemDiamondBoots,
	itemWoodSword,
	itemStoneSword,
	itemIronSword,
	itemDiamondSword,
	itemGoldSword,
	itemBow,

	// Resources
	itemCoal,
	itemIronIngot,
	itemGoldIngot,
	itemDiamond,
	itemStick,
	itemRawPork,
	itemCookedPork,
	itemRottenFlesh,
	itemBone,
	itemArrow,
	itemString,
	itemGunpowder,
}
